### ISSUE TITLE
PKI 

### ISSUE THREAD

**Issue by kevinrue** [s-u/PKI#22]
Was facing the same issue as the last off-topic comment on issue #19 

Thankfully I found the solution in:
https://github.com/erlio/vernemq/issues/206

Now my `~/.R/Makevars` looks like:
```
CFLAGS = -g -O3 -Wall -pedantic -mtune=native -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -I/usr/local/opt/gettext/include
CXXFLAGS = -g -O3 -Wall -pedantic -mtune=native -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -I/usr/local/opt/gettext/include

LDFLAGS = -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -L/usr/local/opt/gettext/lib
CPPFLAGS = -I/usr/local/opt/openssl/include
```
Note the importance of specifying both `-L` **and** `-I` (capital i).
For hours I only found posts giving on the latter.

**Comment by s-u** [comment]
See the comment there - please use the latest version (PKI 0.1-5) which fetches the headers from Apple if you don't have them.

You can certainly use 3rd party library as you do above, but generally it's not a good idea as you openssl won't be maintained and patched for security fixes.

**Comment by kevinrue** [comment]
Dear @s-u 
Apologies, I should have specified: I was using the latest version, and still facing the issue:
```
> packageVersion("PKI")
[1] ‘0.1.5.1’
```
I have spent a few hours over the last couple of days following the different suggestions in #19 and #17  , including `install.packages('PKI',,'http://www.rforge.net/')` all without success.

I also tried not using the 3rd party (removing the instructions from the `Makevars` file and even `brew uninstall openssl`) without luck either.

The first thing that worked for me was what I posted above (I try my best not to post solutions more complicated than they needed to be for myself)

**Comment by bjsmith** [comment]
Thanks Kevin - was facing the same problem and your Makevars flag specification worked for me too!

To help other users searching for a solution, the problem I was getting before this was:

`> install.packages('PKI',,'http://www.rforge.net/')
Installing package into ‘/Users/benjaminsmith/Library/R/3.4/library’
(as ‘lib’ is unspecified)
trying URL 'http://www.rforge.net/src/contrib/PKI_0.1-5.tar.gz'
Content type 'application/x-gzip' length 68047 bytes (66 KB)
==================================================
downloaded 66 KB

Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
  unknown timezone 'zone/tz/2018c.1.0/zoneinfo/America/Los_Angeles'
* installing *source* package ‘PKI’ ...
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... 
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... no
checking for openssl/ssl.h... yes
checking openssl/rsa.h usability... 
configure: WARNING: openssl/ssl.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: openssl/ssl.h: proceeding with the compiler's result
yes
checking openssl/rsa.h presence... no
configure: WARNING: openssl/rsa.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: openssl/rsa.h: proceeding with the compiler's result
checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key_ex... no
configure: error: Cannot find usable crypto library
ERROR: configuration failed for package ‘PKI’
* removing ‘/Users/benjaminsmith/Library/R/3.4/library/PKI’
Warning in install.packages :
  installation of package ‘PKI’ had non-zero exit status`


Then I edited my makevars to Kevin's solution above, and it worked.

**Comment by rrcutler** [comment]
@kevinrue 

After unzipping the package moving it to `/usr/local/lib/R/3.5/site-library`, I tried modifying `/usr/local/lib/R/3.5/site-library/PKI/src/Makevars.in` so that it looked like:
`PKG_CPPFLAGS=@CPPFLAGS@
PKG_LIBS=@LIBS@
CFLAGS = -g -O3 -Wall -pedantic -mtune=native -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -I/usr/local/opt/gettext/include
CXXFLAGS = -g -O3 -Wall -pedantic -mtune=native -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -I/usr/local/opt/gettext/include

LDFLAGS = -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -L/usr/local/opt/gettext/lib
CPPFLAGS = -I/usr/local/opt/openssl/include`

However, I still run into the "configure: error: Cannot find usable crypto library" error. I feel that I am missing something here, any help?

**Comment by s-u** [comment]
Please read basic R documentation - you install packages using ` R CMD INSTALL` or `install.packages()` you CANNOT just unpack random content into the R library.

**Comment by s-u** [comment]
And please stop commenting on this issue, yours have absolutely nothing to do with the above, if you need help, just email me with full error log or open a new issue but make sure you include full error transcript and `config.log`.
